### ISSUE TITLE
Example Site ?

### ISSUE THREAD

**Issue by Welsh44** [nicokaiser/kaiser.gallery#10]
Hi

I'm very impressed by your work and how the website looks.
If I go to https://kaiser.gallery/akkordeonfestival-2023/club-milango/ I can see : 
- a title Club Milango -> ok title of the post
- a description (Club Milango mit Peter M. Haas (Akkordeon), Bernd Dall...) -> description in the frontmatter ?
- photos have a description which can be viewed on hover or in photoswipe. -> exif or something else ?

If you can provide some answers or an example site it would be nice.

Thanks in advance

**Comment by hugo-sid** [comment]
Great work @nicokaiser !

I feel an `exmpleSite` folder with sample content will clear all the confusions or queries that I have.

**Comment by nicokaiser** [comment]
It is like @Welsh44 said. But as soon as I find some time, I will add a small exampleSite to clarify things.

**Comment by nicokaiser** [comment]
I currently do not have time to set up an exampleSite, but here is a short explanation until then:

### Album

content/new-york-2023/index.md

```markdown
---
title: New York 2023
description: A trip to New York City.
date: 2023-02-24
featured_image: DSC01234.jpg
---
```

https://example.com/new-york-2023/ will then include all photos that are in `content/new-york-2023/`.

- `featured_image` can be omitted, then the first photo will be used as album cover, or the first picture with `*feature*` in its filename.
- `private: true` will exclude this album from collection (list) pages, the homepage and RSS feeds. (Currently I'm not sure if sub-albums of private albums might be visible, see #8)
- Photos in the album are sorted ascending by their EXIF date (I might include a `sort_by` parameter)

### Collection

A collection is a list of albums, to be able to create sub-pages like "Travel" which includes all travel albums:

content/travel/_index.md

```markdown
---
title: Travel
description: I travel a lot. Here are some of my recent trips.
feature_image: cover.jpg
---
```

https://example.com/travel/ will list all sub-albums (see above) which live in content/travel/, ordered by descending date.

### Photos

Photos in Albums are displayed (only) through PhotoSwipe. Captions are read from the IPTC/EXIF Caption in the files.

**Comment by Welsh44** [comment]
Great ! That's a very useful explanation to begin. I think it's a real start point.

**Comment by nicokaiser** [comment]
nicokaiser/hugo-theme-gallery now provides an exampleSite folder.
