### ISSUE TITLE
How to show more exif data?

### ISSUE THREAD

**Issue by Sammmmm** [nicokaiser/kaiser.gallery#15]
I'm probably missing something simple, but I can't get the caption to show arbitrary exif data like focal length -- can you point me in the right direction?  It appears you're using the photoswipe dynamic caption plugin but I can't figure out where the caption is specified.

**Comment by Sammmmm** [comment]
For anyone else who is curious: It appears there is some default that I'm unaware of.  Manually specifying what I want overrides that.  E.g. 

```
{{ with $metadata }}
    <span class="pswp-caption-content">{{ .ImageDescription }}</span>
{{ end }}```

I'm sure there's a more elegant way but this worked for me for now

**Comment by nicokaiser** [comment]
You can specify which EXIF fields are being processed in your `hugo.yaml` using the `includeFields`: https://gohugo.io/content-management/image-processing/#exif-data

```yaml
[imaging]
  [imaging.exif]
    includeFields = ".*"
```

Then you can use all available tags (unfortunately only EXIF, since Hugo does not support IPTC yet).
